- hosts: localhost
  gather_facts: no

  tasks:
    - name: Ensure system is up to date
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install my packages
      become: yes
      pacman:
        name:
          - vim
          - htop
          - fish
          - tmux
          - curl
          - wget
          - openssh
          - neofetch
          - clang
          - cmake
          - go
          - git
          - nmap
          - base-devel
          - net-tools
          - iptables-nft
          - wireguard-tools
          - starship
        state: present
        
    - name: Ensure the default editor is set to nano
      lineinfile:
        path: /etc/environment
        line: 'EDITOR=nano'
        state: present
        create: yes  # Create the file if it doesn't exist

    - name: Ensure sudoers.d directory exists
      become: yes
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0750'

    - name: Create sudoers configuration for {{ ansible_user }}
      copy:
        content: |
          # Allow '{{ ansible_user }}' to run any commands without password
          {{ ansible_user }} ALL=(ALL) NOPASSWD: ALL
          Defaults !tty_tickets, timestamp_timeout=0
          Defaults passwd_tries=100
        dest: /etc/sudoers.d/{{ ansible_user }}
        owner: root
        group: root
        mode: '0440'
      when: ansible_user is defined  # Ensure ansible_user is set

    - name: Validate sudoers file
      command: visudo -c
      register: visudo_output
      failed_when: visudo_output.rc != 0
      changed_when: false

    - name: Install yay from AUR
      shell: |
        git clone https://aur.archlinux.org/yay.git &&
        cd yay &&
        makepkg -si --noconfirm
      args:
        creates: yay

    - name: Check if iptables module is loaded
      become: yes
      shell: lsmod | grep -w ip_tables
      register: iptables_module
      ignore_errors: true

    - name: Load iptables module
      become: yes
      command: modprobe ip_tables
      when: iptables_module.rc != 0
    
    - name: Install docker & podman
      become: yes
      pacman:
        name:
          - podman
          - docker
          - docker-compose
        state: present

    - name: Enable and start docker service
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install virtualization packages
      become: yes
      pacman:
        name:
          - virt-manager
          - virt-viewer
          - qemu-full
          - edk2-ovmf
          - vde2
          - ebtables
          - dnsmasq
          - bridge-utils
          - openbsd-netcat
          - libguestfs
        state: present

    - name: Check if lines are already added to /etc/libvirt/libvirtd.conf
      become: yes
      stat:
        path: /etc/libvirt/libvirtd.conf
      register: libvirtd_conf

    - name: Add lines to /etc/libvirt/libvirtd.conf if not already added
      become: yes
      blockinfile:
        path: /etc/libvirt/libvirtd.conf
        block: |
          unix_sock_group = "libvirt"
          unix_sock_ro_perms = "0777"
          unix_sock_rw_perms = "0770"
      when: libvirtd_conf.stat.exists == false

    - name: Add current user to kvm and libvirt groups
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: kvm,libvirt
        append: yes
      when: libvirtd_conf.stat.exists == false

    - name: Enable and start libvirtd service
      become: yes
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Check if br10.xml exists
      stat:
        path: /root/br10.xml
      register: br10_xml

    - name: Copy br10.xml to /root/br10.xml
      become: yes
      copy:
        src: br10.xml
        dest: /root/br10.xml
        owner: root
        group: root
        mode: '0644'
      when: not br10_xml.stat.exists

    - name: Define the network using virsh
      become: yes
      shell: virsh net-define /root/br10.xml
      when: not br10_xml.stat.exists

    - name: Start the network using virsh
      become: yes
      shell: virsh net-start br10
      when: not br10_xml.stat.exists

    - name: Set the network to autostart using virsh
      become: yes
      shell: virsh net-autostart br10
      when: not br10_xml.stat.exists

    - name: Remove kvm_amd module
      become: yes
      command: modprobe -r kvm_amd
      ignore_errors: yes

    - name: Load kvm_amd module with nested virtualization
      become: yes
      command: modprobe kvm_amd nested=1

    - name: Persist kvm_amd configuration
      become: yes
      copy:
        content: "options kvm-intel nested=1"
        dest: /etc/modprobe.d/kvm-intel.conf

    - name: Verify nested virtualization
      command: systool -m kvm_amd -v
      register: systool_output
      changed_when: false

    - debug:
        msg: "Nested virtualization is enabled"
      when: "'nested = Y' in systool_output.stdout"

    - name: Check nested parameter
      command: cat /sys/module/kvm_amd/parameters/nested
      register: nested_param
      changed_when: false
      become: yes

    - debug:
        msg: "Nested parameter is set to 1"
      when: "'Y' in nested_param.stdout"

    - name: Install minikube and kubectl
      become: yes
      pacman:
        name:
          - minikube
          - kubectl
        state: present

    - name: Check if yay is installed
      stat:
        path: /usr/bin/yay
      register: yay_stat

    - name: Install hyprland and other packages using yay
      command: yay -S hyprland nwg-look-bin waybar wpaperd kitty wl-clipboard cliphist wofi grim slurp polkit-gnome gdm --noconfirm
      become: no
      when: yay_stat.stat.exists

    - name: Install nemo firefox flat-remix flat-remix-gtk ttf-font-awesome-5 for Hyprland using yay
      command: yay -S firefox nemo flat-remix flat-remix-gtk ttf-font-awesome-5 --noconfirm
      become: no
      when: yay_stat.stat.exists

    - name: Install nwg-displays using yay [Must be compiled]
      command: yay -S nwg-displays --noconfirm
      become: no
      when: yay_stat.stat.exists

    - name: Install packages for hardware acceleration 
      become: yes
      pacman:
        name:
            - mesa 
            - vulkan-radeon 
            - vulkan-icd-loader 
            - libva-mesa-driver 
            - mesa-vdpau 
            - vulkan-tools
            - radeontop

    - name: Install Flatpak
      become: yes
      pacman:
        name: flatpak
        state: present

    - name: Add Flathub repository
      command: flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install all packages from nerd-fonts group
      become: yes
      pacman:
        name:
          - otf-aurulent-nerd
          - otf-codenewroman-nerd
          - otf-comicshanns-nerd
          - otf-commit-mono-nerd
          - otf-droid-nerd
          - otf-firamono-nerd
          - otf-geist-mono-nerd
          - otf-hasklig-nerd
          - otf-hermit-nerd
          - otf-monaspace-nerd
          - otf-opendyslexic-nerd
          - otf-overpass-nerd
          - ttf-0xproto-nerd
          - ttf-3270-nerd
          - ttf-agave-nerd
          - ttf-anonymouspro-nerd
          - ttf-arimo-nerd
          - ttf-bigblueterminal-nerd
          - ttf-bitstream-vera-mono-nerd
          - ttf-cascadia-code-nerd
          - ttf-cascadia-mono-nerd
          - ttf-cousine-nerd
          - ttf-d2coding-nerd
          - ttf-daddytime-mono-nerd
          - ttf-dejavu-nerd
          - ttf-envycoder-nerd
          - ttf-fantasque-nerd
          - ttf-firacode-nerd
          - ttf-go-nerd
          - ttf-hack-nerd
          - ttf-heavydata-nerd
          - ttf-iawriter-nerd
          - ttf-ibmplex-mono-nerd
          - ttf-inconsolata-go-nerd
          - ttf-inconsolata-lgc-nerd
          - ttf-inconsolata-nerd
          - ttf-intone-nerd
          - ttf-iosevka-nerd
          - ttf-iosevkaterm-nerd
          - ttf-jetbrains-mono-nerd
          - ttf-lekton-nerd
          - ttf-liberation-mono-nerd
          - ttf-lilex-nerd
          - ttf-martian-mono-nerd
          - ttf-meslo-nerd
          - ttf-monofur-nerd
          - ttf-monoid-nerd
          - ttf-mononoki-nerd
          - ttf-mplus-nerd
          - ttf-nerd-fonts-symbols
          - ttf-nerd-fonts-symbols-mono
          - ttf-noto-nerd
          - ttf-profont-nerd
          - ttf-proggyclean-nerd
          - ttf-roboto-mono-nerd
          - ttf-sharetech-mono-nerd
          - ttf-sourcecodepro-nerd
          - ttf-space-mono-nerd
          - ttf-terminus-nerd
          - ttf-tinos-nerd
          - ttf-ubuntu-mono-nerd
          - ttf-ubuntu-nerd
          - ttf-victor-mono-nerd
          - ttf-jetbrains-mono
          - noto-fonts-emoji
        state: present


    - name: Install Asian Characters support
      become: yes
      pacman:
        name:
          - adobe-source-han-serif-cn-fonts 
          - adobe-source-han-serif-jp-fonts 
          - adobe-source-han-serif-kr-fonts
          - adobe-source-han-serif-otc-fonts 
          - adobe-source-han-serif-tw-fonts
        state: present

    - name: Copy configs directory from local to remote .config
      become: yes
      synchronize:
        src: userfolder/
        dest: "/home/{{ ansible_user }}/"
        recursive: yes
        rsync_opts:
          - "--chown={{ ansible_user }}:{{ ansible_user }}"
      delegate_to: localhost

    - name: Ensure the Wallpapers directory exists
      file:
        path: /home/{{ ansible_user }}/Pictures/Wallpapers
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy the wallpapers
      copy:
        src: arch_wallpaper.jpg
        dest: /home/{{ ansible_user }}/Pictures/Wallpapers/arch_wallpaper.jpg
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Enable gdm service
      become: yes
      systemd:
        name: gdm.service
        enabled: yes

    - name: Remove sudo configuration for ansible
      become: yes
      file:
        path: /etc/sudoers.d/{{ ansible_user }}
        state: absent
